#!/bin/bash
set -euo pipefail

echo "============================================"
echo "Azure App Service Python Guide - Deploy"
echo "============================================"
echo ""

if [ -f .env ]; then
  echo "📁 Loading configuration from .env file..."
  set -a
  # shellcheck disable=SC1091
  source .env
  set +a
else
  echo "⚠️  .env file not found. Using default values..."
fi

RESOURCE_GROUP_NAME=${RESOURCE_GROUP_NAME:-"rg-appservice-python"}
LOCATION=${LOCATION:-"eastus"}
BASE_NAME=${BASE_NAME:-"pyapp"}
APP_SERVICE_PLAN_SKU=${APP_SERVICE_PLAN_SKU:-"B1"}
PYTHON_VERSION=${PYTHON_VERSION:-"3.11"}
LOG_ANALYTICS_RETENTION_DAYS=${LOG_ANALYTICS_RETENTION_DAYS:-90}
LOG_LEVEL=${LOG_LEVEL:-"INFO"}
SAMPLING_RATIO=${SAMPLING_RATIO:-"1.0"}
ENABLE_GUNICORN_MULTIWORKERS=${ENABLE_GUNICORN_MULTIWORKERS:-"true"}

echo "Configuration:"
echo "  Resource Group: $RESOURCE_GROUP_NAME"
echo "  Location: $LOCATION"
echo "  Base Name: $BASE_NAME"
echo "  App Service Plan SKU: $APP_SERVICE_PLAN_SKU"
echo "  Python Version: $PYTHON_VERSION"
echo "  Log Analytics Retention: $LOG_ANALYTICS_RETENTION_DAYS days"
echo "  Log Level: $LOG_LEVEL"
echo "  Sampling Ratio: $SAMPLING_RATIO"
echo "  Gunicorn Multiworkers: $ENABLE_GUNICORN_MULTIWORKERS"
echo ""

read -p "Continue with deployment? (y/n) " -n 1 -r
echo ""
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
  echo "Deployment cancelled."
  exit 1
fi

echo ""
echo "Step 1/4: Checking Azure CLI login status..."
if ! az account show > /dev/null 2>&1; then
  echo "❌ Not logged in to Azure. Please run 'az login' first."
  exit 1
fi

SUBSCRIPTION_NAME=$(az account show --query name -o tsv)
echo "✅ Logged in to Azure subscription: $SUBSCRIPTION_NAME"
echo ""

echo "Step 2/4: Creating resource group..."
if az group show --name "$RESOURCE_GROUP_NAME" > /dev/null 2>&1; then
  echo "⚠️  Resource group '$RESOURCE_GROUP_NAME' already exists. Using existing group."
else
  az group create \
    --name "$RESOURCE_GROUP_NAME" \
    --location "$LOCATION" \
    --output none
  echo "✅ Resource group created: $RESOURCE_GROUP_NAME"
fi
echo ""

echo "Step 3/4: Deploying infrastructure (Bicep)..."
echo "⏱️  This may take 3-5 minutes..."
DEPLOYMENT_OUTPUT=$(az deployment group create \
  --resource-group "$RESOURCE_GROUP_NAME" \
  --template-file main.bicep \
  --parameters \
    baseName="$BASE_NAME" \
    location="$LOCATION" \
    appServicePlanSku="$APP_SERVICE_PLAN_SKU" \
    pythonVersion="$PYTHON_VERSION" \
    logAnalyticsRetentionDays="$LOG_ANALYTICS_RETENTION_DAYS" \
    logLevel="$LOG_LEVEL" \
    samplingRatio="$SAMPLING_RATIO" \
    enableGunicornMultiworkers="$ENABLE_GUNICORN_MULTIWORKERS" \
  --output json)

WEB_APP_NAME=$(echo "$DEPLOYMENT_OUTPUT" | jq -r '.properties.outputs.webAppName.value')
WEB_APP_URL=$(echo "$DEPLOYMENT_OUTPUT" | jq -r '.properties.outputs.webAppUrl.value')
APP_INSIGHTS_NAME=$(echo "$DEPLOYMENT_OUTPUT" | jq -r '.properties.outputs.appInsightsName.value')
APP_INSIGHTS_CONNECTION_STRING=$(echo "$DEPLOYMENT_OUTPUT" | jq -r '.properties.outputs.appInsightsConnectionString.value')
LOG_ANALYTICS_NAME=$(echo "$DEPLOYMENT_OUTPUT" | jq -r '.properties.outputs.logAnalyticsWorkspaceName.value')

echo "✅ Infrastructure deployed successfully!"

DEPLOY_OUTPUT_FILE=".deploy-output.env"
cat > "$DEPLOY_OUTPUT_FILE" << EOF
# Deployment Output - Generated by deploy.sh at $(date -u +"%Y-%m-%dT%H:%M:%SZ")

RESOURCE_GROUP_NAME=$RESOURCE_GROUP_NAME
WEB_APP_NAME=$WEB_APP_NAME
APP_INSIGHTS_NAME=$APP_INSIGHTS_NAME
LOG_ANALYTICS_NAME=$LOG_ANALYTICS_NAME
WEB_APP_URL=$WEB_APP_URL
APPLICATIONINSIGHTS_CONNECTION_STRING=$APP_INSIGHTS_CONNECTION_STRING
EOF
echo "📄 Deployment outputs saved to: infra/$DEPLOY_OUTPUT_FILE"
echo ""

echo "Step 4/4: Deploying application code..."
if [ ! -d ../app ]; then
  echo "❌ app directory not found. Make sure you're running this from the infra/ directory."
  exit 1
fi

pushd ../app > /dev/null

echo "📦 Creating deployment package..."
zip -rq app.zip . -x ".venv/*" -x "venv/*" -x "__pycache__/*" -x "*.pyc" -x ".git/*" -x "*.zip"

echo "🚀 Deploying to Azure App Service..."
az webapp deployment source config-zip \
  --name "$WEB_APP_NAME" \
  --resource-group "$RESOURCE_GROUP_NAME" \
  --src app.zip \
  --output none

rm app.zip
popd > /dev/null

echo "✅ Application deployed successfully!"
echo ""

echo "⏱️  Waiting 30 seconds for application to start..."
sleep 30

echo "🔍 Testing health endpoint..."
HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" "$WEB_APP_URL/health")

if [ "$HTTP_STATUS" = "200" ]; then
  echo "✅ Application is healthy!"
else
  echo "⚠️  Application returned HTTP $HTTP_STATUS. It may still be starting up."
  echo "   Wait 1-2 minutes and check: $WEB_APP_URL/health"
fi

echo ""
echo "============================================"
echo "✅ Deployment Completed Successfully!"
echo "============================================"
echo ""
echo "Resource Details:"
echo "  Resource Group:       $RESOURCE_GROUP_NAME"
echo "  Web App:              $WEB_APP_NAME"
echo "  Application Insights: $APP_INSIGHTS_NAME"
echo "  Log Analytics:        $LOG_ANALYTICS_NAME"
echo ""
echo "Application URL:"
echo "  $WEB_APP_URL"
echo ""
