#!/bin/bash
set -e

echo "============================================"
echo "Azure App Service Java Guide - Deployment"
echo "============================================"
echo ""

if [ -f .env ]; then
  echo "📁 Loading configuration from .env file..."
  export $(grep -v '^#' .env | xargs)
else
  echo "⚠️  .env file not found. Using default values..."
fi

RESOURCE_GROUP_NAME=${RESOURCE_GROUP_NAME:-"rg-appservice-java"}
LOCATION=${LOCATION:-"eastus"}
BASE_NAME=${BASE_NAME:-"java-app"}
APP_SERVICE_PLAN_SKU=${APP_SERVICE_PLAN_SKU:-"B1"}
LOG_ANALYTICS_RETENTION_DAYS=${LOG_ANALYTICS_RETENTION_DAYS:-30}
APP_INSIGHTS_SAMPLING_PERCENTAGE=${APP_INSIGHTS_SAMPLING_PERCENTAGE:-100}

echo "Configuration:"
echo "  Resource Group: $RESOURCE_GROUP_NAME"
echo "  Location: $LOCATION"
echo "  Base Name: $BASE_NAME"
echo "  App Service Plan SKU: $APP_SERVICE_PLAN_SKU"
echo "  Log Analytics Retention: $LOG_ANALYTICS_RETENTION_DAYS days"
echo "  App Insights Sampling (%): $APP_INSIGHTS_SAMPLING_PERCENTAGE"
echo ""

read -r -p "Continue with deployment? (y/n) " SHOULD_CONTINUE
if [ "$SHOULD_CONTINUE" != "y" ] && [ "$SHOULD_CONTINUE" != "Y" ]; then
  echo "Deployment cancelled."
  exit 1
fi

echo ""
echo "Step 1/4: Checking Azure CLI login status..."
if ! az account show --output none > /dev/null 2>&1; then
  echo "❌ Not logged in to Azure. Please run 'az login' first."
  exit 1
fi

SUBSCRIPTION_NAME=$(az account show --query name --output tsv)
echo "✅ Logged in to Azure subscription: $SUBSCRIPTION_NAME"
echo ""

echo "Step 2/4: Creating resource group..."
if az group show --name "$RESOURCE_GROUP_NAME" --output none > /dev/null 2>&1; then
  echo "⚠️  Resource group '$RESOURCE_GROUP_NAME' already exists. Using existing group."
else
  az group create \
    --name "$RESOURCE_GROUP_NAME" \
    --location "$LOCATION" \
    --output none
  echo "✅ Resource group created: $RESOURCE_GROUP_NAME"
fi
echo ""

echo "Step 3/4: Deploying infrastructure (Bicep)..."
echo "⏱️  This may take 3-5 minutes..."
DEPLOYMENT_OUTPUT=$(az deployment group create \
  --resource-group "$RESOURCE_GROUP_NAME" \
  --template-file main.bicep \
  --parameters \
    baseName="$BASE_NAME" \
    location="$LOCATION" \
    appServicePlanSku="$APP_SERVICE_PLAN_SKU" \
    logAnalyticsRetentionDays="$LOG_ANALYTICS_RETENTION_DAYS" \
    appInsightsSamplingPercentage="$APP_INSIGHTS_SAMPLING_PERCENTAGE" \
  --output json)

WEB_APP_NAME=$(python3 -c "import json,sys; print(json.load(sys.stdin)['properties']['outputs']['webAppName']['value'])" <<< "$DEPLOYMENT_OUTPUT")
WEB_APP_URL=$(python3 -c "import json,sys; print(json.load(sys.stdin)['properties']['outputs']['webAppUrl']['value'])" <<< "$DEPLOYMENT_OUTPUT")
APP_INSIGHTS_NAME=$(python3 -c "import json,sys; print(json.load(sys.stdin)['properties']['outputs']['appInsightsName']['value'])" <<< "$DEPLOYMENT_OUTPUT")
LOG_ANALYTICS_NAME=$(python3 -c "import json,sys; print(json.load(sys.stdin)['properties']['outputs']['logAnalyticsWorkspaceName']['value'])" <<< "$DEPLOYMENT_OUTPUT")

echo "✅ Infrastructure deployed successfully!"
echo ""

DEPLOY_OUTPUT_FILE=".deploy-output.env"
cat > "$DEPLOY_OUTPUT_FILE" << EOF
# Deployment Output - Generated by deploy.sh at $(date -u +"%Y-%m-%dT%H:%M:%SZ")
RESOURCE_GROUP_NAME=$RESOURCE_GROUP_NAME
APP_NAME=$WEB_APP_NAME
APP_INSIGHTS_NAME=$APP_INSIGHTS_NAME
LOG_ANALYTICS_NAME=$LOG_ANALYTICS_NAME
WEB_APP_URL=$WEB_APP_URL
EOF

echo "📄 Deployment outputs saved to: infra/$DEPLOY_OUTPUT_FILE"
echo ""

echo "Step 4/4: Building and deploying with Maven Plugin..."
SCRIPT_DIR=$(pwd)
APP_DIR="$SCRIPT_DIR/../app"

if [ ! -f "$APP_DIR/pom.xml" ]; then
  echo "❌ pom.xml not found. Run this script from infra/."
  exit 1
fi

cd "$APP_DIR"

RESOURCE_GROUP_NAME="$RESOURCE_GROUP_NAME" \
APP_NAME="$WEB_APP_NAME" \
LOCATION="$LOCATION" \
./mvnw clean package -DskipTests

RESOURCE_GROUP_NAME="$RESOURCE_GROUP_NAME" \
APP_NAME="$WEB_APP_NAME" \
LOCATION="$LOCATION" \
./mvnw azure-webapp:deploy

echo "✅ Application deployed successfully with Maven Plugin!"
echo ""
echo "🔍 Verifying health endpoint..."
HTTP_STATUS=$(curl --silent --output /dev/null --write-out "%{http_code}" "$WEB_APP_URL/health")

if [ "$HTTP_STATUS" = "200" ]; then
  echo "✅ Application is healthy!"
else
  echo "⚠️  Application returned HTTP $HTTP_STATUS. It may still be starting up."
fi

echo ""
echo "============================================"
echo "✅ Deployment Completed Successfully!"
echo "============================================"
echo ""
echo "Resource Details:"
echo "  Resource Group:       $RESOURCE_GROUP_NAME"
echo "  Web App:              $WEB_APP_NAME"
echo "  Application Insights: $APP_INSIGHTS_NAME"
echo "  Log Analytics:        $LOG_ANALYTICS_NAME"
echo ""
echo "Application URL:"
echo "  $WEB_APP_URL"
echo ""
echo "Next Steps:"
echo "  1. Test endpoints:"
echo "     curl $WEB_APP_URL/health"
echo "     curl $WEB_APP_URL/info"
echo "     curl $WEB_APP_URL/api/requests/log-levels"
echo ""
echo "  2. Stream logs:"
echo "     az webapp log tail --name $WEB_APP_NAME --resource-group $RESOURCE_GROUP_NAME"
echo ""
echo "  3. Cleanup when finished:"
echo "     az group delete --name $RESOURCE_GROUP_NAME --yes --no-wait"
echo "============================================"
