spring.application.name=azure-appservice-java-guide
server.port=${PORT:8080}
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=20s

logging.level.root=INFO
logging.level.com.example.guide=DEBUG
